#!/usr/bin/env python3
"""Generate the lane-based AVX/AVX2 SLEIGH files.

Every VEX constructor is written on 64-bit lanes: an XMM operand is two
qwords, a YMM operand is four, and no temporary is wider than the 16 bytes a
memory operand is loaded as. This keeps the lifted p-code within the width
the QCode emulator handles natively while still modelling the full 256-bit
register.

Three files are produced:

  avx_macros.sinc  the lane library: one macro per (operation, lane width)
                   that maps one qword of packed lanes, plus the helpers the
                   constructors compose them with.
  avx.sinc         the regular three-operand packed forms, both VEX.128 and
                   VEX.256, for every operation in TABLE.
  avx2.sinc        nothing yet: the 256-bit integer forms live in avx.sinc
                   next to their 128-bit siblings; the file is kept so the
                   include list is stable.

Irregular instructions (moves, shuffles, permutes, inserts, extracts,
broadcasts, conversions, compares, blends, string compares, gathers and the
VZERO* pair) are hand-written in avx_manual.sinc / avx2_manual.sinc using the
same macros.

The encodings come from `avx_inventory.json`, extracted from the previous
generated files so no opcode is retyped by hand. Run from the repo root:

    python3 scripts/avx_gen.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
X86 = ROOT / "src" / "x86"
INVENTORY = Path(__file__).with_name("avx_inventory.json")

# ---------------------------------------------------------------------------
# The lane library
# ---------------------------------------------------------------------------

LANES = {8: 8, 16: 4, 32: 2, 64: 1}


def lane_slices(width: int) -> list[str]:
    """`[0,8]`, `[8,8]`, ... for one qword of `width`-bit lanes."""
    return [f"[{i * width},{width}]" for i in range(LANES[width])]


def qword_macro(name: str, width: int, lane_expr) -> str:
    """A macro mapping `lane_expr(x_lane, y_lane)` over every lane of a qword.

    `lane_expr` is called with the two source lane texts and returns the
    result lane expression. The result is built in a local and copied out
    last so a caller may alias `dest` with a source.
    """
    if width == 64:
        body = f"    dest = {lane_expr('a', 'b')};"
        return f"macro {name}(dest, a, b) {{\n{body}\n}}\n"
    lines = ["    local x:8 = a; local y:8 = b; local r:8;"]
    for sl in lane_slices(width):
        lines.append(f"    r{sl} = {lane_expr('x' + sl, 'y' + sl)};")
    lines.append("    dest = r;")
    return f"macro {name}(dest, a, b) {{\n" + "\n".join(lines) + "\n}\n"


def select_macro(name: str, width: int, predicate) -> str:
    """Min/max style: pick x where predicate(x, y) holds, else y."""
    if width == 64:
        return (
            f"macro {name}(dest, a, b) {{\n"
            f"    local x:8 = a; local y:8 = b;\n"
            f"    local k:8 = 0 - zext({predicate('x', 'y')});\n"
            f"    dest = (x & k) | (y & ~k);\n}}\n"
        )
    lines = ["    local x:8 = a; local y:8 = b; local k:8;"]
    for sl in lane_slices(width):
        lines.append(f"    k{sl} = 0 - zext({predicate('x' + sl, 'y' + sl)});")
    lines.append("    dest = (x & k) | (y & ~k);")
    return f"macro {name}(dest, a, b) {{\n" + "\n".join(lines) + "\n}\n"


def userop_macro(name: str, op: str) -> str:
    """Saturating and averaging lanes: the emulator evaluates the SSE user-op
    on any operand width, so one qword is passed straight through."""
    return (
        f"macro {name}(dest, a, b) {{ local x:8 = a; local y:8 = b; "
        f"dest = {op}(x, y); }}\n"
    )


def float_macro(name: str, width: int, sse_macro: str) -> str:
    """Float lanes reuse the MXCSR-aware SSE scalar macros lane by lane."""
    lines = ["    local x:8 = a; local y:8 = b; local r:8;"]
    for sl in lane_slices(width):
        lines.append(f"    {sse_macro}(r{sl}, x{sl}, y{sl});")
    lines.append("    dest = r;")
    return f"macro {name}(dest, a, b) {{\n" + "\n".join(lines) + "\n}\n"


def float_unary_macro(name: str, width: int, sse_macro: str) -> str:
    lines = ["    local x:8 = a; local r:8;"]
    for sl in lane_slices(width):
        lines.append(f"    {sse_macro}(r{sl}, x{sl});")
    lines.append("    dest = r;")
    return f"macro {name}(dest, a) {{\n" + "\n".join(lines) + "\n}\n"


def macro_library() -> str:
    out = [
        "# The AVX lane library. Generated by scripts/avx_gen.py; do not edit.\n"
        "#\n"
        "# Every VEX-encoded constructor is written in terms of 64-bit lanes: an\n"
        "# XMM operand is two qwords, a YMM operand is four, and no temporary is\n"
        "# ever wider than the 16 bytes a memory source is loaded as. That keeps\n"
        "# the lifted code inside the emulator's native width while still\n"
        "# expressing the full 256-bit semantics.\n"
        "#\n"
        "# avx_<op><w>(dest, a, b) maps one qword of packed <w>-bit lanes.\n"
        "# avx_zero_upper(reg) clears bits 128-255 of a YMM after a VEX.128 form\n"
        "# wrote its low half. The ZMM upper 256 bits are architecturally zeroed\n"
        "# by every VEX instruction too; they are left untouched because no VEX\n"
        "# form can observe them and the register file names lanes only up to the\n"
        "# YMM width.\n\n"
        "macro avx_zero_upper(reg) {\n"
        "    reg[128,64] = 0:8;\n"
        "    reg[192,64] = 0:8;\n"
        "}\n\n"
        "# Bitwise, width-agnostic.\n"
        "macro avx_and(dest, a, b)  { dest = a & b; }\n"
        "macro avx_andn(dest, a, b) { dest = ~a & b; }\n"
        "macro avx_or(dest, a, b)   { dest = a | b; }\n"
        "macro avx_xor(dest, a, b)  { dest = a ^ b; }\n\n"
    ]
    out.append("# Wrapping integer add and subtract.\n")
    for w in (8, 16, 32, 64):
        out.append(qword_macro(f"avx_add{w}", w, lambda x, y: f"{x} + {y}"))
        out.append(qword_macro(f"avx_sub{w}", w, lambda x, y: f"{x} - {y}"))
    out.append("\n# Low half of the lane product.\n")
    for w in (16, 32):
        out.append(qword_macro(f"avx_mullo{w}", w, lambda x, y: f"{x} * {y}"))
    out.append("\n# Saturating arithmetic and averages, through the SSE user-ops.\n")
    for name, op in [
        ("avx_adds8", "paddsb"), ("avx_adds16", "paddsw"),
        ("avx_addus8", "paddusb"), ("avx_addus16", "paddusw"),
        ("avx_subs8", "psubsb"), ("avx_subs16", "psubsw"),
        ("avx_subus8", "psubusb"), ("avx_subus16", "psubusw"),
        ("avx_avg8", "pavgb"), ("avx_avg16", "pavgw"),
        ("avx_mulhu16", "pmulhuw"), ("avx_madd16", "pmaddwd"),
    ]:
        out.append(userop_macro(name, op))
    out.append("\n# Signed high half of the 16-bit product.\n")
    lines = ["    local x:8 = a; local y:8 = b; local r:8;"]
    for i, sl in enumerate(lane_slices(16)):
        lines.append(f"    local p{i}:4 = sext(x{sl}) * sext(y{sl});")
        lines.append(f"    r{sl} = p{i}[16,16];")
    lines.append("    dest = r;")
    out.append("macro avx_mulhs16(dest, a, b) {\n" + "\n".join(lines) + "\n}\n")
    out.append("\n# Compares: all-ones where the predicate holds.\n")
    for w in (8, 16, 32, 64):
        out.append(qword_macro(f"avx_cmpeq{w}", w, lambda x, y: f"0 - zext({x} == {y})"))
        out.append(qword_macro(f"avx_cmpgt{w}", w, lambda x, y: f"0 - zext({x} s> {y})"))
    out.append("\n# Min and max, signed and unsigned.\n")
    for w in (8, 16, 32):
        out.append(select_macro(f"avx_mins{w}", w, lambda x, y: f"{x} s< {y}"))
        out.append(select_macro(f"avx_maxs{w}", w, lambda x, y: f"{x} s> {y}"))
        out.append(select_macro(f"avx_minu{w}", w, lambda x, y: f"{x} < {y}"))
        out.append(select_macro(f"avx_maxu{w}", w, lambda x, y: f"{x} > {y}"))
    out.append("\n# IEEE lanes, through the MXCSR-aware SSE scalar macros.\n")
    for w, sfx in ((32, "32"), (64, "64")):
        for op in ("add", "sub", "mul", "div", "min", "max"):
            out.append(float_macro(f"avx_f{op}{w}", w, f"sse_{op}{sfx}"))
        out.append(float_unary_macro(f"avx_fsqrt{w}", w, f"sse_sqrt{sfx}"))
    return "".join(out)


# ---------------------------------------------------------------------------
# The regular packed forms
# ---------------------------------------------------------------------------

# mnemonic -> (lane macro, arity). Arity 2 is `dest, src1, src2`; arity 1 is
# `dest, src`.
TABLE: dict[str, tuple[str, int]] = {
    # bitwise
    "VPAND": ("avx_and", 2), "VPANDN": ("avx_andn", 2),
    "VPOR": ("avx_or", 2), "VPXOR": ("avx_xor", 2),
    "VANDPS": ("avx_and", 2), "VANDPD": ("avx_and", 2),
    "VANDNPS": ("avx_andn", 2), "VANDNPD": ("avx_andn", 2),
    "VORPS": ("avx_or", 2), "VORPD": ("avx_or", 2),
    "VXORPS": ("avx_xor", 2), "VXORPD": ("avx_xor", 2),
    # integer add/sub
    "VPADDB": ("avx_add8", 2), "VPADDW": ("avx_add16", 2),
    "VPADDD": ("avx_add32", 2), "VPADDQ": ("avx_add64", 2),
    "VPSUBB": ("avx_sub8", 2), "VPSUBW": ("avx_sub16", 2),
    "VPSUBD": ("avx_sub32", 2), "VPSUBQ": ("avx_sub64", 2),
    "VPADDSB": ("avx_adds8", 2), "VPADDSW": ("avx_adds16", 2),
    "VPADDUSB": ("avx_addus8", 2), "VPADDUSW": ("avx_addus16", 2),
    "VPSUBSB": ("avx_subs8", 2), "VPSUBSW": ("avx_subs16", 2),
    "VPSUBUSB": ("avx_subus8", 2), "VPSUBUSW": ("avx_subus16", 2),
    "VPAVGB": ("avx_avg8", 2), "VPAVGW": ("avx_avg16", 2),
    # multiply
    "VPMULLW": ("avx_mullo16", 2), "VPMULLD": ("avx_mullo32", 2),
    "VPMULHW": ("avx_mulhs16", 2), "VPMULHUW": ("avx_mulhu16", 2),
    "VPMADDWD": ("avx_madd16", 2),
    # compare
    "VPCMPEQB": ("avx_cmpeq8", 2), "VPCMPEQW": ("avx_cmpeq16", 2),
    "VPCMPEQD": ("avx_cmpeq32", 2), "VPCMPEQQ": ("avx_cmpeq64", 2),
    "VPCMPGTB": ("avx_cmpgt8", 2), "VPCMPGTW": ("avx_cmpgt16", 2),
    "VPCMPGTD": ("avx_cmpgt32", 2), "VPCMPGTQ": ("avx_cmpgt64", 2),
    # min/max
    "VPMINSB": ("avx_mins8", 2), "VPMINSW": ("avx_mins16", 2),
    "VPMINSD": ("avx_mins32", 2),
    "VPMAXSB": ("avx_maxs8", 2), "VPMAXSW": ("avx_maxs16", 2),
    "VPMAXSD": ("avx_maxs32", 2),
    "VPMINUB": ("avx_minu8", 2), "VPMINUW": ("avx_minu16", 2),
    "VPMINUD": ("avx_minu32", 2),
    "VPMAXUB": ("avx_maxu8", 2), "VPMAXUW": ("avx_maxu16", 2),
    "VPMAXUD": ("avx_maxu32", 2),
    # packed float
    "VADDPS": ("avx_fadd32", 2), "VADDPD": ("avx_fadd64", 2),
    "VSUBPS": ("avx_fsub32", 2), "VSUBPD": ("avx_fsub64", 2),
    "VMULPS": ("avx_fmul32", 2), "VMULPD": ("avx_fmul64", 2),
    "VDIVPS": ("avx_fdiv32", 2), "VDIVPD": ("avx_fdiv64", 2),
    "VMINPS": ("avx_fmin32", 2), "VMINPD": ("avx_fmin64", 2),
    "VMAXPS": ("avx_fmax32", 2), "VMAXPD": ("avx_fmax64", 2),
    "VSQRTPS": ("avx_fsqrt32", 1), "VSQRTPD": ("avx_fsqrt64", 1),
}

SHAPE_3 = {"XmmReg1,vexVVVV_XmmReg,XmmReg2_m128", "YmmReg1,vexVVVV_YmmReg,YmmReg2_m256"}
SHAPE_2 = {"XmmReg1,XmmReg2_m128", "YmmReg1,YmmReg2_m256"}


def constructor_128(name: str, operands: str, pattern: str, macro: str, arity: int) -> str:
    pattern = pattern.replace("(XmmReg1 & ZmmReg1)", "(XmmReg1 & YmmReg1)")
    src1 = "vexVVVV_XmmReg" if arity == 2 else None
    calls = []
    for lane, off in ((0, 0), (1, 64)):
        args = [f"YmmReg1[{off},64]"]
        if src1:
            args.append(f"{src1}[{off},64]")
        args.append(f"m[{off},64]")
        calls.append(f"    {macro}({', '.join(args)});")
    body = "    local m:16 = XmmReg2_m128;\n" + "\n".join(calls) + "\n    avx_zero_upper(YmmReg1);"
    return f":{name} {operands} is {pattern}\n{{\n{body}\n}}\n"


def constructor_256(name: str, operands: str, pattern: str, macro: str, arity: int) -> str:
    # Read the source halves through the half-width subtables; keep the full
    # operand in the display and in the pattern so disassembly is unchanged.
    pattern = pattern.replace("(YmmReg1 & ZmmReg1) ... & YmmReg2_m256",
                              "(YmmReg1 & YmmReg2_m256) ... & YmmReg2_m256_L & YmmReg2_m256_H")
    if arity == 2:
        pattern = pattern.replace("& vexVVVV_YmmReg;",
                                  "& vexVVVV_YmmReg & vexVVVV_YmmReg_L & vexVVVV_YmmReg_H;")
    assert "YmmReg2_m256_L" in pattern, (name, pattern)
    calls = []
    for off, half, hoff in ((0, "lo", 0), (64, "lo", 64), (128, "hi", 0), (192, "hi", 64)):
        args = [f"YmmReg1[{off},64]"]
        if arity == 2:
            v = "vexVVVV_YmmReg_L" if half == "lo" else "vexVVVV_YmmReg_H"
            args.append(f"{v}[{hoff},64]")
        args.append(f"{half}[{hoff},64]")
        calls.append(f"    {macro}({', '.join(args)});")
    body = "    local lo:16 = YmmReg2_m256_L;\n    local hi:16 = YmmReg2_m256_H;\n" + "\n".join(calls)
    return f":{name} {operands} is {pattern}\n{{\n{body}\n}}\n"


def packed_file(inventory: list[dict]) -> tuple[str, set[str]]:
    out = [
        "#@family avx\n"
        "# The regular three-operand packed AVX and AVX2 forms, on 64-bit lanes.\n"
        "# Generated by scripts/avx_gen.py; do not edit. The lane macros live in\n"
        "# avx_macros.sinc, the half-width operands in avx_operands.sinc, and the\n"
        "# irregular instructions in avx_manual.sinc / avx2_manual.sinc.\n\n"
    ]
    done: set[str] = set()
    seen_headers: set[str] = set()
    for row in inventory:
        name = row["name"]
        if name not in TABLE:
            continue
        macro, arity = TABLE[name]
        shape = re.sub(r"\s+", "", row["operands"])
        expect = SHAPE_3 if arity == 2 else SHAPE_2
        if shape not in expect:
            continue
        key = (name, shape)
        if key in seen_headers:
            continue
        seen_headers.add(key)
        gen = constructor_128 if shape.startswith("Xmm") else constructor_256
        out.append(f"# {name}\n")
        out.append(gen(name, row["operands"], row["pattern"], macro, arity))
        out.append("\n")
        done.add(name)
    return "".join(out), done


def main() -> int:
    inventory = json.loads(INVENTORY.read_text())
    (X86 / "avx_macros.sinc").write_text(macro_library())
    packed, done = packed_file(inventory)
    (X86 / "avx.sinc").write_text(packed)
    (X86 / "avx2.sinc").write_text(
        "#@family avx\n"
        "# Reserved for AVX2-only forms that need their own file. The 256-bit\n"
        "# integer forms are generated into avx.sinc beside their 128-bit\n"
        "# siblings. Generated by scripts/avx_gen.py; do not edit.\n"
    )
    missing = sorted(set(TABLE) - done)
    if missing:
        print("no inventory match for:", " ".join(missing), file=sys.stderr)
    print(f"generated {len(done)} mnemonics")
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
