#!/usr/bin/env python3
"""Generate the lane-based AVX/AVX2 SLEIGH files.

Every VEX constructor is written on 64-bit lanes: an XMM operand is two
qwords, a YMM operand is four, and no temporary is wider than the 16 bytes a
memory operand is loaded as. This keeps the lifted p-code within the width
the QCode emulator handles natively while still modelling the full 256-bit
register.

Three files are produced:

  avx_macros.sinc  the lane library: one macro per (operation, lane width)
                   that maps one qword of packed lanes, plus the helpers the
                   constructors compose them with.
  avx.sinc         the regular three-operand packed forms, both VEX.128 and
                   VEX.256, for every operation in TABLE.
  avx2.sinc        nothing yet: the 256-bit integer forms live in avx.sinc
                   next to their 128-bit siblings; the file is kept so the
                   include list is stable.

Irregular instructions (moves, shuffles, permutes, inserts, extracts,
broadcasts, conversions, compares, blends, string compares, gathers and the
VZERO* pair) are hand-written in avx_manual.sinc / avx2_manual.sinc using the
same macros.

The encodings come from `avx_inventory.json`, extracted from the previous
generated files so no opcode is retyped by hand. Run from the repo root:

    python3 scripts/avx_gen.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
X86 = ROOT / "src" / "x86"
INVENTORY = Path(__file__).with_name("avx_inventory.json")

# ---------------------------------------------------------------------------
# The lane library
# ---------------------------------------------------------------------------

LANES = {8: 8, 16: 4, 32: 2, 64: 1}


def lane_slices(width: int) -> list[str]:
    """`[0,8]`, `[8,8]`, ... for one qword of `width`-bit lanes."""
    return [f"[{i * width},{width}]" for i in range(LANES[width])]


def qword_macro(name: str, width: int, lane_expr) -> str:
    """A macro mapping `lane_expr(x_lane, y_lane)` over every lane of a qword.

    `lane_expr` is called with the two source lane texts and returns the
    result lane expression. The result is built in a local and copied out
    last so a caller may alias `dest` with a source.
    """
    if width == 64:
        body = f"    dest = {lane_expr('a', 'b')};"
        return f"macro {name}(dest, a, b) {{\n{body}\n}}\n"
    lines = ["    local x:8 = a; local y:8 = b; local r:8;"]
    for sl in lane_slices(width):
        lines.append(f"    r{sl} = {lane_expr('x' + sl, 'y' + sl)};")
    lines.append("    dest = r;")
    return f"macro {name}(dest, a, b) {{\n" + "\n".join(lines) + "\n}\n"


def select_macro(name: str, width: int, predicate) -> str:
    """Min/max style: pick x where predicate(x, y) holds, else y."""
    if width == 64:
        return (
            f"macro {name}(dest, a, b) {{\n"
            f"    local x:8 = a; local y:8 = b;\n"
            f"    local k:8 = 0 - zext({predicate('x', 'y')});\n"
            f"    dest = (x & k) | (y & ~k);\n}}\n"
        )
    lines = ["    local x:8 = a; local y:8 = b; local k:8;"]
    for sl in lane_slices(width):
        lines.append(f"    k{sl} = 0 - zext({predicate('x' + sl, 'y' + sl)});")
    lines.append("    dest = (x & k) | (y & ~k);")
    return f"macro {name}(dest, a, b) {{\n" + "\n".join(lines) + "\n}\n"


def userop_macro(name: str, op: str) -> str:
    """Saturating and averaging lanes: the emulator evaluates the SSE user-op
    on any operand width, so one qword is passed straight through."""
    return (
        f"macro {name}(dest, a, b) {{ local x:8 = a; local y:8 = b; "
        f"dest = {op}(x, y); }}\n"
    )


def float_macro(name: str, width: int, sse_macro: str) -> str:
    """Float lanes reuse the MXCSR-aware SSE scalar macros lane by lane."""
    lines = ["    local x:8 = a; local y:8 = b; local r:8;"]
    for sl in lane_slices(width):
        lines.append(f"    {sse_macro}(r{sl}, x{sl}, y{sl});")
    lines.append("    dest = r;")
    return f"macro {name}(dest, a, b) {{\n" + "\n".join(lines) + "\n}\n"


def float_unary_macro(name: str, width: int, sse_macro: str) -> str:
    lines = ["    local x:8 = a; local r:8;"]
    for sl in lane_slices(width):
        lines.append(f"    {sse_macro}(r{sl}, x{sl});")
    lines.append("    dest = r;")
    return f"macro {name}(dest, a) {{\n" + "\n".join(lines) + "\n}\n"


def macro_library() -> str:
    out = [
        "# The AVX lane library. Generated by scripts/avx_gen.py; do not edit.\n"
        "#\n"
        "# Every VEX-encoded constructor is written in terms of 64-bit lanes: an\n"
        "# XMM operand is two qwords, a YMM operand is four, and no temporary is\n"
        "# ever wider than the 16 bytes a memory source is loaded as. That keeps\n"
        "# the lifted code inside the emulator's native width while still\n"
        "# expressing the full 256-bit semantics.\n"
        "#\n"
        "# avx_<op><w>(dest, a, b) maps one qword of packed <w>-bit lanes.\n"
        "# avx_zero_upper(reg) clears bits 128-255 of a YMM after a VEX.128 form\n"
        "# wrote its low half. The ZMM upper 256 bits are architecturally zeroed\n"
        "# by every VEX instruction too; they are left untouched because no VEX\n"
        "# form can observe them and the register file names lanes only up to the\n"
        "# YMM width.\n\n"
        "macro avx_zero_upper(reg) {\n"
        "    reg[128,64] = 0:8;\n"
        "    reg[192,64] = 0:8;\n"
        "}\n\n"
        "# Bitwise, width-agnostic.\n"
        "macro avx_and(dest, a, b)  { dest = a & b; }\n"
        "macro avx_andn(dest, a, b) { dest = ~a & b; }\n"
        "macro avx_or(dest, a, b)   { dest = a | b; }\n"
        "macro avx_xor(dest, a, b)  { dest = a ^ b; }\n\n"
    ]
    out.append("# Wrapping integer add and subtract.\n")
    for w in (8, 16, 32, 64):
        out.append(qword_macro(f"avx_add{w}", w, lambda x, y: f"{x} + {y}"))
        out.append(qword_macro(f"avx_sub{w}", w, lambda x, y: f"{x} - {y}"))
    out.append("\n# Low half of the lane product.\n")
    for w in (16, 32):
        out.append(qword_macro(f"avx_mullo{w}", w, lambda x, y: f"{x} * {y}"))
    out.append("\n# Saturating arithmetic and averages, through the SSE user-ops.\n")
    for name, op in [
        ("avx_adds8", "paddsb"), ("avx_adds16", "paddsw"),
        ("avx_addus8", "paddusb"), ("avx_addus16", "paddusw"),
        ("avx_subs8", "psubsb"), ("avx_subs16", "psubsw"),
        ("avx_subus8", "psubusb"), ("avx_subus16", "psubusw"),
        ("avx_avg8", "pavgb"), ("avx_avg16", "pavgw"),
        ("avx_mulhu16", "pmulhuw"), ("avx_madd16", "pmaddwd"),
    ]:
        out.append(userop_macro(name, op))
    out.append("\n# Signed high half of the 16-bit product.\n")
    lines = ["    local x:8 = a; local y:8 = b; local r:8;"]
    for i, sl in enumerate(lane_slices(16)):
        lines.append(f"    local p{i}:4 = sext(x{sl}) * sext(y{sl});")
        lines.append(f"    r{sl} = p{i}[16,16];")
    lines.append("    dest = r;")
    out.append("macro avx_mulhs16(dest, a, b) {\n" + "\n".join(lines) + "\n}\n")
    out.append("\n# Compares: all-ones where the predicate holds.\n")
    for w in (8, 16, 32, 64):
        out.append(qword_macro(f"avx_cmpeq{w}", w, lambda x, y: f"0 - zext({x} == {y})"))
        out.append(qword_macro(f"avx_cmpgt{w}", w, lambda x, y: f"0 - zext({x} s> {y})"))
    out.append("\n# Min and max, signed and unsigned.\n")
    for w in (8, 16, 32):
        out.append(select_macro(f"avx_mins{w}", w, lambda x, y: f"{x} s< {y}"))
        out.append(select_macro(f"avx_maxs{w}", w, lambda x, y: f"{x} s> {y}"))
        out.append(select_macro(f"avx_minu{w}", w, lambda x, y: f"{x} < {y}"))
        out.append(select_macro(f"avx_maxu{w}", w, lambda x, y: f"{x} > {y}"))
    out.append("\n# Unsigned 32x32->64 and signed 32x32->64 products of the even lanes.\n")
    out.append("macro avx_muludq(dest, a, b) { local x:8 = a; local y:8 = b; "
               "dest = zext(x[0,32]) * zext(y[0,32]); }\n")
    out.append("macro avx_muldq(dest, a, b) { local x:8 = a; local y:8 = b; "
               "dest = sext(x[0,32]) * sext(y[0,32]); }\n")
    out.append("\n# Rounded, scaled signed 16-bit product: (a*b + 0x4000) >> 15.\n")
    lines = ["    local x:8 = a; local y:8 = b; local r:8;"]
    for i, sl in enumerate(lane_slices(16)):
        lines.append(f"    local p{i}:4 = ((sext(x{sl}) * sext(y{sl})) + 0x4000) s>> 15;")
        lines.append(f"    r{sl} = p{i}[0,16];")
    lines.append("    dest = r;")
    out.append("macro avx_mulhrs16(dest, a, b) {\n" + "\n".join(lines) + "\n}\n")
    out.append("\n# Absolute value and sign transfer.\n")
    for w in (8, 16, 32):
        out.append(qword_macro(f"avx_abs{w}", w,
            lambda x, y: f"({x} ^ ({x} s>> {w-1})) - ({x} s>> {w-1})"))
        # psign: b<0 -> -a; b==0 -> 0; b>0 -> a
        out.append(qword_macro(f"avx_sign{w}", w,
            lambda x, y, w=w: f"(({x} ^ ({y} s>> {w-1})) - ({y} s>> {w-1})) * zext({y} != 0)"))
    out.append("\n# Sum of absolute byte differences into one qword.\n")
    lines = ["    local x:8 = a; local y:8 = b; local s:8 = 0;"]
    for sl in lane_slices(8):
        lines.append(f"    local d{sl[1:-3].replace(',','_')}:1 = x{sl} - y{sl};")
    for sl in lane_slices(8):
        n = sl[1:-3].replace(',', '_')
        lines.append(f"    s = s + zext((d{n} ^ (d{n} s>> 7)) - (d{n} s>> 7));")
    lines.append("    dest = s;")
    # keep byte differences unsigned: recompute with proper abs of unsigned lanes
    lines = ["    local x:8 = a; local y:8 = b; local s:8 = 0;"]
    for i, sl in enumerate(lane_slices(8)):
        lines.append(f"    local gt{i}:1 = x{sl} > y{sl};")
        lines.append(f"    local d{i}:1 = (x{sl} - y{sl}) * zext(gt{i}) + (y{sl} - x{sl}) * zext(!gt{i});")
        lines.append(f"    s = s + zext(d{i});")
    lines.append("    dest = s;")
    out.append("macro avx_sadbw(dest, a, b) {\n" + "\n".join(lines) + "\n}\n")
    out.append("\n# Horizontal pairs within one qword: dest lanes = (a0+a1, a2+a3, ...).\n")
    for w in (16, 32):
        n = LANES[w]
        lines = ["    local x:8 = a; local r:8;"]
        for i in range(n // 2):
            lines.append(f"    r[{i*w},{w}] = x[{2*i*w},{w}] + x[{(2*i+1)*w},{w}];")
        for i in range(n // 2, n):
            lines.append(f"    r[{i*w},{w}] = 0;")
        lines.append("    dest = r;")
        out.append(f"macro avx_hpair_add{w}(dest, a) {{\n" + "\n".join(lines) + "\n}\n")
    out.append("\n# Shift every lane of a qword by one count; counts past the lane width\n"
               "# clear the lane (or fill with the sign for arithmetic shifts).\n")
    for w in (16, 32, 64):
        for kind, op in (("sll", "<<"), ("srl", ">>"), ("sra", "s>>")):
            lines = ["    local x:8 = a; local n:8 = count;",
                     f"    local over:8 = zext(n > {w-1});",
                     f"    local amount:8 = (n & (over - 1)) | (over * {w});"]
            if w == 64:
                lines.append(f"    dest = x {op} amount;")
            else:
                lines.append("    local r:8;")
                for sl in lane_slices(w):
                    lines.append(f"    r{sl} = x{sl} {op} amount;")
                lines.append("    dest = r;")
            out.append(f"macro avx_{kind}{w}(dest, a, count) {{\n" + "\n".join(lines) + "\n}\n")
    out.append("\n# Per-lane variable shifts (AVX2): each lane has its own count.\n")
    for w in (32, 64):
        for kind, op in (("sllv", "<<"), ("srlv", ">>"), ("srav", "s>>")):
            lines = ["    local x:8 = a; local c:8 = b; local r:8;"]
            for sl in lane_slices(w):
                lines.append(f"    local n{sl[1:-3].replace(',','_')}:8 = zext(c{sl});")
            for sl in lane_slices(w):
                n = sl[1:-3].replace(',', '_')
                lines.append(f"    local over{n}:8 = zext(n{n} > {w-1});")
                lines.append(f"    r{sl} = x{sl} {op} ((n{n} & (over{n} - 1)) | (over{n} * {w}));")
            lines.append("    dest = r;")
            out.append(f"macro avx_{kind}{w}(dest, a, b) {{\n" + "\n".join(lines) + "\n}\n")
    out.append("\n# Interleave the low (or high) halves of two qwords: unpack.\n")
    for w in (8, 16, 32):
        n = LANES[w]
        for half, base in (("lo", 0), ("hi", n // 2)):
            lines = ["    local x:8 = a; local y:8 = b; local r:8;"]
            for i in range(n // 2):
                lines.append(f"    r[{(2*i)*w},{w}] = x[{(base+i)*w},{w}];")
                lines.append(f"    r[{(2*i+1)*w},{w}] = y[{(base+i)*w},{w}];")
            lines.append("    dest = r;")
            out.append(f"macro avx_unpack{half}{w}(dest, a, b) {{\n" + "\n".join(lines) + "\n}\n")
    out.append("\n# Saturating packs: a qword of 2w-bit lanes narrows to w-bit lanes.\n")
    for name, sw, dw, signed, kind in (
        ("avx_packss16", 16, 8, True, "s"), ("avx_packus16", 16, 8, False, "u"),
        ("avx_packss32", 32, 16, True, "s"), ("avx_packus32", 32, 16, False, "u"),
    ):
        hi = (1 << (dw - 1)) - 1 if signed else (1 << dw) - 1
        lo = -(1 << (dw - 1)) if signed else 0
        lines = ["    local x:8 = a; local r:4;"]
        for i, sl in enumerate(lane_slices(sw)):
            v = f"x{sl}"
            if signed:
                lines.append(f"    local c{i}:{sw//8} = {v};")
                lines.append(f"    local h{i}:1 = c{i} s> {hi};")
                lines.append(f"    local l{i}:1 = c{i} s< {lo};")
                lines.append(f"    local s{i}:{sw//8} = ({hi} * zext(h{i})) + ({lo & ((1<<sw)-1)} * zext(l{i})) + (c{i} * zext(!h{i} && !l{i}));")
            else:
                lines.append(f"    local c{i}:{sw//8} = {v};")
                lines.append(f"    local h{i}:1 = c{i} s> {hi};")
                lines.append(f"    local l{i}:1 = c{i} s< 0;")
                lines.append(f"    local s{i}:{sw//8} = ({hi} * zext(h{i})) + (c{i} * zext(!h{i} && !l{i}));")
            lines.append(f"    r[{i*dw},{dw}] = s{i}[0,{dw}];")
        lines.append("    dest = r;")
        out.append(f"macro {name}(dest, a) {{\n" + "\n".join(lines) + "\n}\n")
    out.append("\n# Widening moves: a half-qword of narrow lanes to a qword of wide ones.\n"
               "# `signed` selects sext over zext.\n")
    for (sw, dw) in ((8, 16), (16, 32), (8, 32)):
        n = 64 // dw
        lines = [f"    local x:{n*sw//8} = a; local r:8; local s:1 = signed;"]
        for i in range(n):
            lines.append(f"    r[{i*dw},{dw}] = (sext(x[{i*sw},{sw}]) * zext(s)) | (zext(x[{i*sw},{sw}]) * zext(!s));")
        lines.append("    dest = r;")
        out.append(f"macro avx_ext{sw}to{dw}(dest, a, signed) {{\n" + "\n".join(lines) + "\n}\n")
    out.append("\n# The eight sign bits of a qword's bytes, packed into one byte.\n")
    lines = ["    local x:8 = a;",
             "    dest = " + " | ".join(f"(zext(x[{i*8+7},1]) << {i})" for i in range(8)) + ";"]
    out.append("macro avx_bytemask(dest, a) {\n" + "\n".join(lines) + "\n}\n")
    out.append("\n# IEEE lanes, through the MXCSR-aware SSE scalar macros.\n")
    for w, sfx in ((32, "32"), (64, "64")):
        for op in ("add", "sub", "mul", "div", "min", "max"):
            out.append(float_macro(f"avx_f{op}{w}", w, f"sse_{op}{sfx}"))
        out.append(float_unary_macro(f"avx_fsqrt{w}", w, f"sse_sqrt{sfx}"))
    return "".join(out)


# ---------------------------------------------------------------------------
# The regular packed forms
# ---------------------------------------------------------------------------

# mnemonic -> (lane macro, arity). Arity 2 is `dest, src1, src2`; arity 1 is
# `dest, src`.
TABLE: dict[str, tuple[str, int]] = {
    # bitwise
    "VPAND": ("avx_and", 2), "VPANDN": ("avx_andn", 2),
    "VPOR": ("avx_or", 2), "VPXOR": ("avx_xor", 2),
    "VANDPS": ("avx_and", 2), "VANDPD": ("avx_and", 2),
    "VANDNPS": ("avx_andn", 2), "VANDNPD": ("avx_andn", 2),
    "VORPS": ("avx_or", 2), "VORPD": ("avx_or", 2),
    "VXORPS": ("avx_xor", 2), "VXORPD": ("avx_xor", 2),
    # integer add/sub
    "VPADDB": ("avx_add8", 2), "VPADDW": ("avx_add16", 2),
    "VPADDD": ("avx_add32", 2), "VPADDQ": ("avx_add64", 2),
    "VPSUBB": ("avx_sub8", 2), "VPSUBW": ("avx_sub16", 2),
    "VPSUBD": ("avx_sub32", 2), "VPSUBQ": ("avx_sub64", 2),
    "VPADDSB": ("avx_adds8", 2), "VPADDSW": ("avx_adds16", 2),
    "VPADDUSB": ("avx_addus8", 2), "VPADDUSW": ("avx_addus16", 2),
    "VPSUBSB": ("avx_subs8", 2), "VPSUBSW": ("avx_subs16", 2),
    "VPSUBUSB": ("avx_subus8", 2), "VPSUBUSW": ("avx_subus16", 2),
    "VPAVGB": ("avx_avg8", 2), "VPAVGW": ("avx_avg16", 2),
    # multiply
    "VPMULLW": ("avx_mullo16", 2), "VPMULLD": ("avx_mullo32", 2),
    "VPMULHW": ("avx_mulhs16", 2), "VPMULHUW": ("avx_mulhu16", 2),
    "VPMADDWD": ("avx_madd16", 2),
    # compare
    "VPCMPEQB": ("avx_cmpeq8", 2), "VPCMPEQW": ("avx_cmpeq16", 2),
    "VPCMPEQD": ("avx_cmpeq32", 2), "VPCMPEQQ": ("avx_cmpeq64", 2),
    "VPCMPGTB": ("avx_cmpgt8", 2), "VPCMPGTW": ("avx_cmpgt16", 2),
    "VPCMPGTD": ("avx_cmpgt32", 2), "VPCMPGTQ": ("avx_cmpgt64", 2),
    # min/max
    "VPMINSB": ("avx_mins8", 2), "VPMINSW": ("avx_mins16", 2),
    "VPMINSD": ("avx_mins32", 2),
    "VPMAXSB": ("avx_maxs8", 2), "VPMAXSW": ("avx_maxs16", 2),
    "VPMAXSD": ("avx_maxs32", 2),
    "VPMINUB": ("avx_minu8", 2), "VPMINUW": ("avx_minu16", 2),
    "VPMINUD": ("avx_minu32", 2),
    "VPMAXUB": ("avx_maxu8", 2), "VPMAXUW": ("avx_maxu16", 2),
    "VPMAXUD": ("avx_maxu32", 2),
    # packed float
    "VADDPS": ("avx_fadd32", 2), "VADDPD": ("avx_fadd64", 2),
    "VSUBPS": ("avx_fsub32", 2), "VSUBPD": ("avx_fsub64", 2),
    "VMULPS": ("avx_fmul32", 2), "VMULPD": ("avx_fmul64", 2),
    "VDIVPS": ("avx_fdiv32", 2), "VDIVPD": ("avx_fdiv64", 2),
    "VMINPS": ("avx_fmin32", 2), "VMINPD": ("avx_fmin64", 2),
    "VMAXPS": ("avx_fmax32", 2), "VMAXPD": ("avx_fmax64", 2),
    "VSQRTPS": ("avx_fsqrt32", 1), "VSQRTPD": ("avx_fsqrt64", 1),
}

SHAPE_3 = {"XmmReg1,vexVVVV_XmmReg,XmmReg2_m128", "YmmReg1,vexVVVV_YmmReg,YmmReg2_m256"}
SHAPE_2 = {"XmmReg1,XmmReg2_m128", "YmmReg1,YmmReg2_m256"}

# Operations on one 128-bit lane at a time. The body template is given the
# destination qwords `d0`/`d1`, first-source qwords `a0`/`a1`, and second-
# source qwords `b0`/`b1` (locals for `a`/`b` so the two qwords of a source
# can be read after the first destination qword is written).
# A VEX.256 form applies the body to both halves; that is exactly how AVX2
# defines every packed integer op and the in-lane shuffles.
TABLE_128: dict[str, tuple[str, int]] = {
    # unpack: low halves interleave the low qwords, high halves the high ones
    "VPUNPCKLBW": ("avx_unpacklo8({d0}, {a0}, {b0}); avx_unpackhi8({d1}, {a0}, {b0});", 2),
    "VPUNPCKHBW": ("avx_unpacklo8({d0}, {a1}, {b1}); avx_unpackhi8({d1}, {a1}, {b1});", 2),
    "VPUNPCKLWD": ("avx_unpacklo16({d0}, {a0}, {b0}); avx_unpackhi16({d1}, {a0}, {b0});", 2),
    "VPUNPCKHWD": ("avx_unpacklo16({d0}, {a1}, {b1}); avx_unpackhi16({d1}, {a1}, {b1});", 2),
    "VPUNPCKLDQ": ("avx_unpacklo32({d0}, {a0}, {b0}); avx_unpackhi32({d1}, {a0}, {b0});", 2),
    "VPUNPCKHDQ": ("avx_unpacklo32({d0}, {a1}, {b1}); avx_unpackhi32({d1}, {a1}, {b1});", 2),
    "VPUNPCKLQDQ": ("{d0} = {a0}; {d1} = {b0};", 2),
    "VPUNPCKHQDQ": ("{d0} = {a1}; {d1} = {b1};", 2),
    "VUNPCKLPS": ("avx_unpacklo32({d0}, {a0}, {b0}); avx_unpackhi32({d1}, {a0}, {b0});", 2),
    "VUNPCKHPS": ("avx_unpacklo32({d0}, {a1}, {b1}); avx_unpackhi32({d1}, {a1}, {b1});", 2),
    "VUNPCKLPD": ("{d0} = {a0}; {d1} = {b0};", 2),
    "VUNPCKHPD": ("{d0} = {a1}; {d1} = {b1};", 2),
    # pack: a's four qwords... a lane narrows both qwords of a then of b
    "VPACKSSWB": ("local pa0:4; avx_packss16(pa0, {a0}); local pa1:4; avx_packss16(pa1, {a1}); "
                  "local pb0:4; avx_packss16(pb0, {b0}); local pb1:4; avx_packss16(pb1, {b1}); "
                  "{d0} = (zext(pa1) << 32) | zext(pa0); {d1} = (zext(pb1) << 32) | zext(pb0);", 2),
    "VPACKUSWB": ("local pa0:4; avx_packus16(pa0, {a0}); local pa1:4; avx_packus16(pa1, {a1}); "
                  "local pb0:4; avx_packus16(pb0, {b0}); local pb1:4; avx_packus16(pb1, {b1}); "
                  "{d0} = (zext(pa1) << 32) | zext(pa0); {d1} = (zext(pb1) << 32) | zext(pb0);", 2),
    "VPACKSSDW": ("local pa0:4; avx_packss32(pa0, {a0}); local pa1:4; avx_packss32(pa1, {a1}); "
                  "local pb0:4; avx_packss32(pb0, {b0}); local pb1:4; avx_packss32(pb1, {b1}); "
                  "{d0} = (zext(pa1) << 32) | zext(pa0); {d1} = (zext(pb1) << 32) | zext(pb0);", 2),
    "VPACKUSDW": ("local pa0:4; avx_packus32(pa0, {a0}); local pa1:4; avx_packus32(pa1, {a1}); "
                  "local pb0:4; avx_packus32(pb0, {b0}); local pb1:4; avx_packus32(pb1, {b1}); "
                  "{d0} = (zext(pa1) << 32) | zext(pa0); {d1} = (zext(pb1) << 32) | zext(pb0);", 2),
    # horizontal add/sub: dest = (pairs of a, pairs of b)
    "VPHADDW": ("local ha0:8; avx_hpair_add16(ha0, {a0}); local ha1:8; avx_hpair_add16(ha1, {a1}); "
                "local hb0:8; avx_hpair_add16(hb0, {b0}); local hb1:8; avx_hpair_add16(hb1, {b1}); "
                "{d0} = (ha1 << 32) | (ha0 & 0xffffffff); {d1} = (hb1 << 32) | (hb0 & 0xffffffff);", 2),
    "VPHADDD": ("local ha0:8; avx_hpair_add32(ha0, {a0}); local ha1:8; avx_hpair_add32(ha1, {a1}); "
                "local hb0:8; avx_hpair_add32(hb0, {b0}); local hb1:8; avx_hpair_add32(hb1, {b1}); "
                "{d0} = (ha1 << 32) | (ha0 & 0xffffffff); {d1} = (hb1 << 32) | (hb0 & 0xffffffff);", 2),
    # even-lane widening multiplies
    "VPMULUDQ": ("avx_muludq({d0}, {a0}, {b0}); avx_muludq({d1}, {a1}, {b1});", 2),
    "VPMULDQ": ("avx_muldq({d0}, {a0}, {b0}); avx_muldq({d1}, {a1}, {b1});", 2),
    # sum of absolute differences per qword
    "VPSADBW": ("avx_sadbw({d0}, {a0}, {b0}); avx_sadbw({d1}, {a1}, {b1});", 2),
    # rounded scaled multiply
    "VPMULHRSW": ("avx_mulhrs16({d0}, {a0}, {b0}); avx_mulhrs16({d1}, {a1}, {b1});", 2),
    # abs / sign (unary uses only a)
    "VPABSB": ("avx_abs8({d0}, {a0}, {a0}); avx_abs8({d1}, {a1}, {a1});", 1),
    "VPABSW": ("avx_abs16({d0}, {a0}, {a0}); avx_abs16({d1}, {a1}, {a1});", 1),
    "VPABSD": ("avx_abs32({d0}, {a0}, {a0}); avx_abs32({d1}, {a1}, {a1});", 1),
    "VPSIGNB": ("avx_sign8({d0}, {a0}, {b0}); avx_sign8({d1}, {a1}, {b1});", 2),
    "VPSIGNW": ("avx_sign16({d0}, {a0}, {b0}); avx_sign16({d1}, {a1}, {b1});", 2),
    "VPSIGND": ("avx_sign32({d0}, {a0}, {b0}); avx_sign32({d1}, {a1}, {b1});", 2),
    # addsub: even lanes subtract, odd lanes add
    "VADDSUBPS": ("local q0:8; local q1:8; sse_sub32(q0[0,32], {a0}[0,32], {b0}[0,32]); sse_add32(q0[32,32], {a0}[32,32], {b0}[32,32]); "
                  "sse_sub32(q1[0,32], {a1}[0,32], {b1}[0,32]); sse_add32(q1[32,32], {a1}[32,32], {b1}[32,32]); {d0} = q0; {d1} = q1;", 2),
    "VADDSUBPD": ("sse_sub64({d0}, {a0}, {b0}); sse_add64({d1}, {a1}, {b1});", 2),
    # horizontal float add/sub
    "VHADDPS": ("local q0:8; local q1:8; sse_add32(q0[0,32], {a0}[0,32], {a0}[32,32]); sse_add32(q0[32,32], {a1}[0,32], {a1}[32,32]); "
                "sse_add32(q1[0,32], {b0}[0,32], {b0}[32,32]); sse_add32(q1[32,32], {b1}[0,32], {b1}[32,32]); {d0} = q0; {d1} = q1;", 2),
    "VHSUBPS": ("local q0:8; local q1:8; sse_sub32(q0[0,32], {a0}[0,32], {a0}[32,32]); sse_sub32(q0[32,32], {a1}[0,32], {a1}[32,32]); "
                "sse_sub32(q1[0,32], {b0}[0,32], {b0}[32,32]); sse_sub32(q1[32,32], {b1}[0,32], {b1}[32,32]); {d0} = q0; {d1} = q1;", 2),
    "VHADDPD": ("sse_add64({d0}, {a0}, {a1}); sse_add64({d1}, {b0}, {b1});", 2),
    "VHSUBPD": ("sse_sub64({d0}, {a0}, {a1}); sse_sub64({d1}, {b0}, {b1});", 2),
}

# Shifts by a count in the low qword of an XMM/m128 operand, or an imm8.
# name -> (lane macro, lane width)
TABLE_SHIFT: dict[str, str] = {
    "VPSLLW": "avx_sll16", "VPSLLD": "avx_sll32", "VPSLLQ": "avx_sll64",
    "VPSRLW": "avx_srl16", "VPSRLD": "avx_srl32", "VPSRLQ": "avx_srl64",
    "VPSRAW": "avx_sra16", "VPSRAD": "avx_sra32",
}
# AVX2 per-lane variable shifts, plain three-operand qword macros.
TABLE_VSHIFT: dict[str, str] = {
    "VPSLLVD": "avx_sllv32", "VPSLLVQ": "avx_sllv64",
    "VPSRLVD": "avx_srlv32", "VPSRLVQ": "avx_srlv64",
    "VPSRAVD": "avx_srav32",
}


def constructor_128(name: str, operands: str, pattern: str, macro: str, arity: int) -> str:
    pattern = pattern.replace("(XmmReg1 & ZmmReg1)", "(XmmReg1 & YmmReg1)")
    src1 = "vexVVVV_XmmReg" if arity == 2 else None
    calls = []
    for lane, off in ((0, 0), (1, 64)):
        args = [f"YmmReg1[{off},64]"]
        if src1:
            args.append(f"{src1}[{off},64]")
        args.append(f"m[{off},64]")
        calls.append(f"    {macro}({', '.join(args)});")
    body = "    local m:16 = XmmReg2_m128;\n" + "\n".join(calls) + "\n    avx_zero_upper(YmmReg1);"
    return f":{name} {operands} is {pattern}\n{{\n{body}\n}}\n"


def constructor_256(name: str, operands: str, pattern: str, macro: str, arity: int) -> str:
    # Read the source halves through the half-width subtables; keep the full
    # operand in the display and in the pattern so disassembly is unchanged.
    pattern = pattern.replace("(YmmReg1 & ZmmReg1) ... & YmmReg2_m256",
                              "(YmmReg1 & YmmReg2_m256) ... & YmmReg2_m256_L & YmmReg2_m256_H")
    if arity == 2:
        pattern = pattern.replace("& vexVVVV_YmmReg;",
                                  "& vexVVVV_YmmReg & vexVVVV_YmmReg_L & vexVVVV_YmmReg_H;")
    assert "YmmReg2_m256_L" in pattern, (name, pattern)
    calls = []
    for off, half, hoff in ((0, "lo", 0), (64, "lo", 64), (128, "hi", 0), (192, "hi", 64)):
        args = [f"YmmReg1[{off},64]"]
        if arity == 2:
            v = "vexVVVV_YmmReg_L" if half == "lo" else "vexVVVV_YmmReg_H"
            args.append(f"{v}[{hoff},64]")
        args.append(f"{half}[{hoff},64]")
        calls.append(f"    {macro}({', '.join(args)});")
    body = "    local lo:16 = YmmReg2_m256_L;\n    local hi:16 = YmmReg2_m256_H;\n" + "\n".join(calls)
    return f":{name} {operands} is {pattern}\n{{\n{body}\n}}\n"


_LANE_COUNTER = [0]


# Hand-written bodies keyed by (mnemonic, operand shape). The emitter binds
# `m` to the r/m operand (loaded at its width), `va` to the vvvv operand as a
# 16-byte local when present, `vlo`/`vhi` to its halves for YMM forms, and
# `lo`/`hi` to the halves of a YMM r/m operand. Every body writes lanes of
# YmmReg1 (or the named destination) and never a value wider than 16 bytes.
SCALAR32 = ("    local va:16 = vexVVVV_XmmReg;\n"
            "    {op}(YmmReg1[0,32], va[0,32], m);\n"
            "    YmmReg1[32,32] = va[32,32];\n"
            "    YmmReg1[64,64] = va[64,64];\n"
            "    avx_zero_upper(YmmReg1);")
SCALAR64 = ("    local va:16 = vexVVVV_XmmReg;\n"
            "    {op}(YmmReg1[0,64], va[0,64], m);\n"
            "    YmmReg1[64,64] = va[64,64];\n"
            "    avx_zero_upper(YmmReg1);")
SCALAR32_U = ("    local va:16 = vexVVVV_XmmReg;\n"
              "    {op}(YmmReg1[0,32], m);\n"
              "    YmmReg1[32,32] = va[32,32];\n"
              "    YmmReg1[64,64] = va[64,64];\n"
              "    avx_zero_upper(YmmReg1);")
SCALAR64_U = ("    local va:16 = vexVVVV_XmmReg;\n"
              "    {op}(YmmReg1[0,64], m);\n"
              "    YmmReg1[64,64] = va[64,64];\n"
              "    avx_zero_upper(YmmReg1);")

MANUAL: dict[tuple[str, str], str] = {}


def _scalar(name, w, op, unary=False):
    shape = f"XmmReg1,vexVVVV_XmmReg,XmmReg2_m{w}"
    tpl = {(32, False): SCALAR32, (64, False): SCALAR64,
           (32, True): SCALAR32_U, (64, True): SCALAR64_U}[(w, unary)]
    MANUAL[(name, shape)] = tpl.format(op=op)


for _op in ("add", "sub", "mul", "div", "min", "max"):
    _scalar(f"V{_op.upper()}SS", 32, f"sse_{_op}32")
    _scalar(f"V{_op.upper()}SD", 64, f"sse_{_op}64")
_scalar("VSQRTSS", 32, "sse_sqrt32", unary=True)
_scalar("VSQRTSD", 64, "sse_sqrt64", unary=True)

MANUAL.update({
    # rounding: scalar keeps vvvv's upper lanes; packed rounds every lane
    ("VROUNDSS", "XmmReg1,vexVVVV_XmmReg,XmmReg2_m32,imm8"):
        "    local va:16 = vexVVVV_XmmReg;\n"
        "    sse_round32(YmmReg1[0,32], m, imm8:1);\n"
        "    YmmReg1[32,32] = va[32,32];\n    YmmReg1[64,64] = va[64,64];\n"
        "    avx_zero_upper(YmmReg1);",
    ("VROUNDSD", "XmmReg1,vexVVVV_XmmReg,XmmReg2_m64,imm8"):
        "    local va:16 = vexVVVV_XmmReg;\n"
        "    sse_round64(YmmReg1[0,64], m, imm8:1);\n"
        "    YmmReg1[64,64] = va[64,64];\n"
        "    avx_zero_upper(YmmReg1);",
    ("VROUNDPS", "XmmReg1,XmmReg2_m128,imm8"):
        "    sse_round32(YmmReg1[0,32], m[0,32], imm8:1);\n    sse_round32(YmmReg1[32,32], m[32,32], imm8:1);\n"
        "    sse_round32(YmmReg1[64,32], m[64,32], imm8:1);\n    sse_round32(YmmReg1[96,32], m[96,32], imm8:1);\n"
        "    avx_zero_upper(YmmReg1);",
    ("VROUNDPS", "YmmReg1,YmmReg2_m256,imm8"):
        "    sse_round32(YmmReg1[0,32], lo[0,32], imm8:1);\n    sse_round32(YmmReg1[32,32], lo[32,32], imm8:1);\n"
        "    sse_round32(YmmReg1[64,32], lo[64,32], imm8:1);\n    sse_round32(YmmReg1[96,32], lo[96,32], imm8:1);\n"
        "    sse_round32(YmmReg1[128,32], hi[0,32], imm8:1);\n    sse_round32(YmmReg1[160,32], hi[32,32], imm8:1);\n"
        "    sse_round32(YmmReg1[192,32], hi[64,32], imm8:1);\n    sse_round32(YmmReg1[224,32], hi[96,32], imm8:1);",
    ("VROUNDPD", "XmmReg1,XmmReg2_m128,imm8"):
        "    sse_round64(YmmReg1[0,64], m[0,64], imm8:1);\n    sse_round64(YmmReg1[64,64], m[64,64], imm8:1);\n"
        "    avx_zero_upper(YmmReg1);",
    ("VROUNDPD", "YmmReg1,YmmReg2_m256,imm8"):
        "    sse_round64(YmmReg1[0,64], lo[0,64], imm8:1);\n    sse_round64(YmmReg1[64,64], lo[64,64], imm8:1);\n"
        "    sse_round64(YmmReg1[128,64], hi[0,64], imm8:1);\n    sse_round64(YmmReg1[192,64], hi[64,64], imm8:1);",
    # ordered / unordered scalar compares into EFLAGS
    ("VCOMISS", "XmmReg1,XmmReg2_m32"): "    sse_comis32(XmmReg1[0,32], m, 1:1);",
    ("VCOMISD", "XmmReg1,XmmReg2_m64"): "    sse_comis64(XmmReg1[0,64], m, 1:1);",
    ("VUCOMISS", "XmmReg1,XmmReg2_m32"): "    sse_comis32(XmmReg1[0,32], m, 0:1);",
    ("VUCOMISD", "XmmReg1,XmmReg2_m64"): "    sse_comis64(XmmReg1[0,64], m, 0:1);",
    # integer <-> float conversions
    ("VCVTSI2SS", "XmmReg1,vexVVVV_XmmReg,rm32"):
        "    local va:16 = vexVVVV_XmmReg;\n    sse_i4_to_f32(YmmReg1[0,32], rm32);\n"
        "    YmmReg1[32,32] = va[32,32];\n    YmmReg1[64,64] = va[64,64];\n    avx_zero_upper(YmmReg1);",
    ("VCVTSI2SS", "XmmReg1,vexVVVV_XmmReg,rm64"):
        "    local va:16 = vexVVVV_XmmReg;\n    sse_i8_to_f32(YmmReg1[0,32], rm64);\n"
        "    YmmReg1[32,32] = va[32,32];\n    YmmReg1[64,64] = va[64,64];\n    avx_zero_upper(YmmReg1);",
    ("VCVTSI2SD", "XmmReg1,vexVVVV_XmmReg,rm32"):
        "    local va:16 = vexVVVV_XmmReg;\n    sse_i4_to_f64(YmmReg1[0,64], rm32);\n"
        "    YmmReg1[64,64] = va[64,64];\n    avx_zero_upper(YmmReg1);",
    ("VCVTSI2SD", "XmmReg1,vexVVVV_XmmReg,rm64"):
        "    local va:16 = vexVVVV_XmmReg;\n    sse_i8_to_f64(YmmReg1[0,64], rm64);\n"
        "    YmmReg1[64,64] = va[64,64];\n    avx_zero_upper(YmmReg1);",
    ("VCVTSS2SI", "Reg32,XmmReg2_m32"): "    local rc:1; sse_rc(rc);\n    sse_f32_to_i4(Reg32, m, rc);\n    build check_Reg32_dest;",
    ("VCVTSS2SI", "Reg64,XmmReg2_m32"): "    local rc:1; sse_rc(rc);\n    sse_f32_to_i8(Reg64, m, rc);",
    ("VCVTSD2SI", "Reg32,XmmReg2_m64"): "    local rc:1; sse_rc(rc);\n    sse_f64_to_i4(Reg32, m, rc);\n    build check_Reg32_dest;",
    ("VCVTSD2SI", "Reg64,XmmReg2_m64"): "    local rc:1; sse_rc(rc);\n    sse_f64_to_i8(Reg64, m, rc);",
    ("VCVTTSS2SI", "Reg32,XmmReg2_m32"): "    sse_f32_to_i4(Reg32, m, 3:1);\n    build check_Reg32_dest;",
    ("VCVTTSS2SI", "Reg64,XmmReg2_m32"): "    sse_f32_to_i8(Reg64, m, 3:1);",
    ("VCVTTSD2SI", "Reg32,XmmReg2_m64"): "    sse_f64_to_i4(Reg32, m, 3:1);\n    build check_Reg32_dest;",
    ("VCVTTSD2SI", "Reg64,XmmReg2_m64"): "    sse_f64_to_i8(Reg64, m, 3:1);",
    ("VCVTSS2SD", "XmmReg1,vexVVVV_XmmReg,XmmReg2_m32"):
        "    local va:16 = vexVVVV_XmmReg;\n    sse_widen32(YmmReg1[0,64], m);\n"
        "    YmmReg1[64,64] = va[64,64];\n    avx_zero_upper(YmmReg1);",
    ("VCVTSD2SS", "XmmReg1,vexVVVV_XmmReg,XmmReg2_m64"):
        "    local va:16 = vexVVVV_XmmReg;\n    sse_narrow64(YmmReg1[0,32], m);\n"
        "    YmmReg1[32,32] = va[32,32];\n    YmmReg1[64,64] = va[64,64];\n    avx_zero_upper(YmmReg1);",
    ("VCVTDQ2PS", "XmmReg1,XmmReg2_m128"):
        "    sse_i4_to_f32(YmmReg1[0,32], m[0,32]);\n    sse_i4_to_f32(YmmReg1[32,32], m[32,32]);\n"
        "    sse_i4_to_f32(YmmReg1[64,32], m[64,32]);\n    sse_i4_to_f32(YmmReg1[96,32], m[96,32]);\n    avx_zero_upper(YmmReg1);",
    ("VCVTDQ2PS", "YmmReg1,YmmReg2_m256"):
        "    sse_i4_to_f32(YmmReg1[0,32], lo[0,32]);\n    sse_i4_to_f32(YmmReg1[32,32], lo[32,32]);\n"
        "    sse_i4_to_f32(YmmReg1[64,32], lo[64,32]);\n    sse_i4_to_f32(YmmReg1[96,32], lo[96,32]);\n"
        "    sse_i4_to_f32(YmmReg1[128,32], hi[0,32]);\n    sse_i4_to_f32(YmmReg1[160,32], hi[32,32]);\n"
        "    sse_i4_to_f32(YmmReg1[192,32], hi[64,32]);\n    sse_i4_to_f32(YmmReg1[224,32], hi[96,32]);",
    ("VCVTPS2DQ", "XmmReg1,XmmReg2_m128"):
        "    local rc:1; sse_rc(rc);\n"
        "    sse_f32_to_i4(YmmReg1[0,32], m[0,32], rc);\n    sse_f32_to_i4(YmmReg1[32,32], m[32,32], rc);\n"
        "    sse_f32_to_i4(YmmReg1[64,32], m[64,32], rc);\n    sse_f32_to_i4(YmmReg1[96,32], m[96,32], rc);\n    avx_zero_upper(YmmReg1);",
    ("VCVTPS2DQ", "YmmReg1,YmmReg2_m256"):
        "    local rc:1; sse_rc(rc);\n"
        "    sse_f32_to_i4(YmmReg1[0,32], lo[0,32], rc);\n    sse_f32_to_i4(YmmReg1[32,32], lo[32,32], rc);\n"
        "    sse_f32_to_i4(YmmReg1[64,32], lo[64,32], rc);\n    sse_f32_to_i4(YmmReg1[96,32], lo[96,32], rc);\n"
        "    sse_f32_to_i4(YmmReg1[128,32], hi[0,32], rc);\n    sse_f32_to_i4(YmmReg1[160,32], hi[32,32], rc);\n"
        "    sse_f32_to_i4(YmmReg1[192,32], hi[64,32], rc);\n    sse_f32_to_i4(YmmReg1[224,32], hi[96,32], rc);",
    ("VCVTTPS2DQ", "XmmReg1,XmmReg2_m128"):
        "    sse_f32_to_i4(YmmReg1[0,32], m[0,32], 3:1);\n    sse_f32_to_i4(YmmReg1[32,32], m[32,32], 3:1);\n"
        "    sse_f32_to_i4(YmmReg1[64,32], m[64,32], 3:1);\n    sse_f32_to_i4(YmmReg1[96,32], m[96,32], 3:1);\n    avx_zero_upper(YmmReg1);",
    ("VCVTTPS2DQ", "YmmReg1,YmmReg2_m256"):
        "    sse_f32_to_i4(YmmReg1[0,32], lo[0,32], 3:1);\n    sse_f32_to_i4(YmmReg1[32,32], lo[32,32], 3:1);\n"
        "    sse_f32_to_i4(YmmReg1[64,32], lo[64,32], 3:1);\n    sse_f32_to_i4(YmmReg1[96,32], lo[96,32], 3:1);\n"
        "    sse_f32_to_i4(YmmReg1[128,32], hi[0,32], 3:1);\n    sse_f32_to_i4(YmmReg1[160,32], hi[32,32], 3:1);\n"
        "    sse_f32_to_i4(YmmReg1[192,32], hi[64,32], 3:1);\n    sse_f32_to_i4(YmmReg1[224,32], hi[96,32], 3:1);",
    # double <-> single/int, where the narrower side is half the width
    ("VCVTPS2PD", "XmmReg1,XmmReg2_m64"):
        "    sse_widen32(YmmReg1[0,64], m[0,32]);\n    sse_widen32(YmmReg1[64,64], m[32,32]);\n    avx_zero_upper(YmmReg1);",
    ("VCVTPS2PD", "YmmReg1,XmmReg2_m128"):
        "    sse_widen32(YmmReg1[0,64], m[0,32]);\n    sse_widen32(YmmReg1[64,64], m[32,32]);\n"
        "    sse_widen32(YmmReg1[128,64], m[64,32]);\n    sse_widen32(YmmReg1[192,64], m[96,32]);",
    ("VCVTPD2PS", "XmmReg1,XmmReg2_m128"):
        "    sse_narrow64(YmmReg1[0,32], m[0,64]);\n    sse_narrow64(YmmReg1[32,32], m[64,64]);\n"
        "    YmmReg1[64,64] = 0:8;\n    avx_zero_upper(YmmReg1);",
    ("VCVTPD2PS", "XmmReg1,YmmReg2_m256"):
        "    sse_narrow64(YmmReg1[0,32], lo[0,64]);\n    sse_narrow64(YmmReg1[32,32], lo[64,64]);\n"
        "    sse_narrow64(YmmReg1[64,32], hi[0,64]);\n    sse_narrow64(YmmReg1[96,32], hi[64,64]);\n    avx_zero_upper(YmmReg1);",
    ("VCVTDQ2PD", "XmmReg1,XmmReg2_m64"):
        "    sse_i4_to_f64(YmmReg1[0,64], m[0,32]);\n    sse_i4_to_f64(YmmReg1[64,64], m[32,32]);\n    avx_zero_upper(YmmReg1);",
    ("VCVTDQ2PD", "YmmReg1,XmmReg2_m128"):
        "    sse_i4_to_f64(YmmReg1[0,64], m[0,32]);\n    sse_i4_to_f64(YmmReg1[64,64], m[32,32]);\n"
        "    sse_i4_to_f64(YmmReg1[128,64], m[64,32]);\n    sse_i4_to_f64(YmmReg1[192,64], m[96,32]);",
    ("VCVTPD2DQ", "XmmReg1,XmmReg2_m128"):
        "    local rc:1; sse_rc(rc);\n    sse_f64_to_i4(YmmReg1[0,32], m[0,64], rc);\n    sse_f64_to_i4(YmmReg1[32,32], m[64,64], rc);\n"
        "    YmmReg1[64,64] = 0:8;\n    avx_zero_upper(YmmReg1);",
    ("VCVTPD2DQ", "XmmReg1,YmmReg2_m256"):
        "    local rc:1; sse_rc(rc);\n    sse_f64_to_i4(YmmReg1[0,32], lo[0,64], rc);\n    sse_f64_to_i4(YmmReg1[32,32], lo[64,64], rc);\n"
        "    sse_f64_to_i4(YmmReg1[64,32], hi[0,64], rc);\n    sse_f64_to_i4(YmmReg1[96,32], hi[64,64], rc);\n    avx_zero_upper(YmmReg1);",
    ("VCVTTPD2DQ", "XmmReg1,XmmReg2_m128"):
        "    sse_f64_to_i4(YmmReg1[0,32], m[0,64], 3:1);\n    sse_f64_to_i4(YmmReg1[32,32], m[64,64], 3:1);\n"
        "    YmmReg1[64,64] = 0:8;\n    avx_zero_upper(YmmReg1);",
    ("VCVTTPD2DQ", "XmmReg1,YmmReg2_m256"):
        "    sse_f64_to_i4(YmmReg1[0,32], lo[0,64], 3:1);\n    sse_f64_to_i4(YmmReg1[32,32], lo[64,64], 3:1);\n"
        "    sse_f64_to_i4(YmmReg1[64,32], hi[0,64], 3:1);\n    sse_f64_to_i4(YmmReg1[96,32], hi[64,64], 3:1);\n    avx_zero_upper(YmmReg1);",
    # test: ZF on and, CF on andn, over the whole operand
    ("VPTEST", "XmmReg1,XmmReg2_m128"):
        "    local x:16 = XmmReg1;\n    ZF = (m & x) == 0;\n    CF = (m & ~x) == 0;\n    AF = 0; OF = 0; PF = 0; SF = 0;",
    ("VPTEST", "YmmReg1,YmmReg2_m256"):
        "    local xl:16 = XmmReg1;\n    local xh:16 = YmmReg1_H;\n"
        "    ZF = ((lo & xl) | (hi & xh)) == 0;\n    CF = ((lo & ~xl) | (hi & ~xh)) == 0;\n    AF = 0; OF = 0; PF = 0; SF = 0;",
    # sign / zero extension moves; the source is the low part of the r/m
    ("VPMOVSXBW", "XmmReg1,XmmReg2_m64"): "    avx_ext8to16(YmmReg1[0,64], m[0,32], 1:1);\n    avx_ext8to16(YmmReg1[64,64], m[32,32], 1:1);\n    avx_zero_upper(YmmReg1);",
    ("VPMOVSXBW", "YmmReg1,XmmReg2_m128"): "    avx_ext8to16(YmmReg1[0,64], m[0,32], 1:1);\n    avx_ext8to16(YmmReg1[64,64], m[32,32], 1:1);\n    avx_ext8to16(YmmReg1[128,64], m[64,32], 1:1);\n    avx_ext8to16(YmmReg1[192,64], m[96,32], 1:1);",
    ("VPMOVZXBW", "XmmReg1,XmmReg2_m64"): "    avx_ext8to16(YmmReg1[0,64], m[0,32], 0:1);\n    avx_ext8to16(YmmReg1[64,64], m[32,32], 0:1);\n    avx_zero_upper(YmmReg1);",
    ("VPMOVZXBW", "YmmReg1,XmmReg2_m128"): "    avx_ext8to16(YmmReg1[0,64], m[0,32], 0:1);\n    avx_ext8to16(YmmReg1[64,64], m[32,32], 0:1);\n    avx_ext8to16(YmmReg1[128,64], m[64,32], 0:1);\n    avx_ext8to16(YmmReg1[192,64], m[96,32], 0:1);",
    ("VPMOVSXBD", "XmmReg1,XmmReg2_m32"): "    avx_ext8to32(YmmReg1[0,64], m[0,16], 1:1);\n    avx_ext8to32(YmmReg1[64,64], m[16,16], 1:1);\n    avx_zero_upper(YmmReg1);",
    ("VPMOVSXBD", "YmmReg1,XmmReg2_m64"): "    avx_ext8to32(YmmReg1[0,64], m[0,16], 1:1);\n    avx_ext8to32(YmmReg1[64,64], m[16,16], 1:1);\n    avx_ext8to32(YmmReg1[128,64], m[32,16], 1:1);\n    avx_ext8to32(YmmReg1[192,64], m[48,16], 1:1);",
    ("VPMOVZXBD", "XmmReg1,XmmReg2_m32"): "    avx_ext8to32(YmmReg1[0,64], m[0,16], 0:1);\n    avx_ext8to32(YmmReg1[64,64], m[16,16], 0:1);\n    avx_zero_upper(YmmReg1);",
    ("VPMOVZXBD", "YmmReg1,XmmReg2_m64"): "    avx_ext8to32(YmmReg1[0,64], m[0,16], 0:1);\n    avx_ext8to32(YmmReg1[64,64], m[16,16], 0:1);\n    avx_ext8to32(YmmReg1[128,64], m[32,16], 0:1);\n    avx_ext8to32(YmmReg1[192,64], m[48,16], 0:1);",
    ("VPMOVSXBQ", "XmmReg1,XmmReg2_m16"): "    YmmReg1[0,64] = sext(m[0,8]);\n    YmmReg1[64,64] = sext(m[8,8]);\n    avx_zero_upper(YmmReg1);",
    ("VPMOVSXBQ", "YmmReg1,XmmReg2_m32"): "    YmmReg1[0,64] = sext(m[0,8]);\n    YmmReg1[64,64] = sext(m[8,8]);\n    YmmReg1[128,64] = sext(m[16,8]);\n    YmmReg1[192,64] = sext(m[24,8]);",
    ("VPMOVZXBQ", "XmmReg1,XmmReg2_m16"): "    YmmReg1[0,64] = zext(m[0,8]);\n    YmmReg1[64,64] = zext(m[8,8]);\n    avx_zero_upper(YmmReg1);",
    ("VPMOVZXBQ", "YmmReg1,XmmReg2_m32"): "    YmmReg1[0,64] = zext(m[0,8]);\n    YmmReg1[64,64] = zext(m[8,8]);\n    YmmReg1[128,64] = zext(m[16,8]);\n    YmmReg1[192,64] = zext(m[24,8]);",
    ("VPMOVSXWD", "XmmReg1,XmmReg2_m64"): "    avx_ext16to32(YmmReg1[0,64], m[0,32], 1:1);\n    avx_ext16to32(YmmReg1[64,64], m[32,32], 1:1);\n    avx_zero_upper(YmmReg1);",
    ("VPMOVSXWD", "YmmReg1,XmmReg2_m128"): "    avx_ext16to32(YmmReg1[0,64], m[0,32], 1:1);\n    avx_ext16to32(YmmReg1[64,64], m[32,32], 1:1);\n    avx_ext16to32(YmmReg1[128,64], m[64,32], 1:1);\n    avx_ext16to32(YmmReg1[192,64], m[96,32], 1:1);",
    ("VPMOVZXWD", "XmmReg1,XmmReg2_m64"): "    avx_ext16to32(YmmReg1[0,64], m[0,32], 0:1);\n    avx_ext16to32(YmmReg1[64,64], m[32,32], 0:1);\n    avx_zero_upper(YmmReg1);",
    ("VPMOVZXWD", "YmmReg1,XmmReg2_m128"): "    avx_ext16to32(YmmReg1[0,64], m[0,32], 0:1);\n    avx_ext16to32(YmmReg1[64,64], m[32,32], 0:1);\n    avx_ext16to32(YmmReg1[128,64], m[64,32], 0:1);\n    avx_ext16to32(YmmReg1[192,64], m[96,32], 0:1);",
    ("VPMOVSXWQ", "XmmReg1,XmmReg2_m32"): "    YmmReg1[0,64] = sext(m[0,16]);\n    YmmReg1[64,64] = sext(m[16,16]);\n    avx_zero_upper(YmmReg1);",
    ("VPMOVSXWQ", "YmmReg1,XmmReg2_m64"): "    YmmReg1[0,64] = sext(m[0,16]);\n    YmmReg1[64,64] = sext(m[16,16]);\n    YmmReg1[128,64] = sext(m[32,16]);\n    YmmReg1[192,64] = sext(m[48,16]);",
    ("VPMOVZXWQ", "XmmReg1,XmmReg2_m32"): "    YmmReg1[0,64] = zext(m[0,16]);\n    YmmReg1[64,64] = zext(m[16,16]);\n    avx_zero_upper(YmmReg1);",
    ("VPMOVZXWQ", "YmmReg1,XmmReg2_m64"): "    YmmReg1[0,64] = zext(m[0,16]);\n    YmmReg1[64,64] = zext(m[16,16]);\n    YmmReg1[128,64] = zext(m[32,16]);\n    YmmReg1[192,64] = zext(m[48,16]);",
    ("VPMOVSXDQ", "XmmReg1,XmmReg2_m64"): "    YmmReg1[0,64] = sext(m[0,32]);\n    YmmReg1[64,64] = sext(m[32,32]);\n    avx_zero_upper(YmmReg1);",
    ("VPMOVSXDQ", "YmmReg1,XmmReg2_m128"): "    YmmReg1[0,64] = sext(m[0,32]);\n    YmmReg1[64,64] = sext(m[32,32]);\n    YmmReg1[128,64] = sext(m[64,32]);\n    YmmReg1[192,64] = sext(m[96,32]);",
    ("VPMOVZXDQ", "XmmReg1,XmmReg2_m64"): "    YmmReg1[0,64] = zext(m[0,32]);\n    YmmReg1[64,64] = zext(m[32,32]);\n    avx_zero_upper(YmmReg1);",
    ("VPMOVZXDQ", "YmmReg1,XmmReg2_m128"): "    YmmReg1[0,64] = zext(m[0,32]);\n    YmmReg1[64,64] = zext(m[32,32]);\n    YmmReg1[128,64] = zext(m[64,32]);\n    YmmReg1[192,64] = zext(m[96,32]);",
    # sign-bit masks into a GPR
    ("VMOVMSKPS", "Reg32,XmmReg2"):
        "    local x:16 = XmmReg2;\n    Reg32 = zext(x[31,1]) | (zext(x[63,1]) << 1) | (zext(x[95,1]) << 2) | (zext(x[127,1]) << 3);\n    build check_Reg32_dest;",
    ("VMOVMSKPS", "Reg32,YmmReg2"):
        "    local x:16 = YmmReg2_L;\n    local y:16 = YmmReg2_H;\n"
        "    Reg32 = zext(x[31,1]) | (zext(x[63,1]) << 1) | (zext(x[95,1]) << 2) | (zext(x[127,1]) << 3)\n"
        "          | (zext(y[31,1]) << 4) | (zext(y[63,1]) << 5) | (zext(y[95,1]) << 6) | (zext(y[127,1]) << 7);\n    build check_Reg32_dest;",
    ("VMOVMSKPD", "Reg32,XmmReg2"):
        "    local x:16 = XmmReg2;\n    Reg32 = zext(x[63,1]) | (zext(x[127,1]) << 1);\n    build check_Reg32_dest;",
    ("VMOVMSKPD", "Reg32,YmmReg2"):
        "    local x:16 = YmmReg2_L;\n    local y:16 = YmmReg2_H;\n"
        "    Reg32 = zext(x[63,1]) | (zext(x[127,1]) << 1) | (zext(y[63,1]) << 2) | (zext(y[127,1]) << 3);\n    build check_Reg32_dest;",
    ("VPMOVMSKB", "Reg32,XmmReg2"):
        "    local x:16 = XmmReg2;\n    local r:4; avx_bytemask(r[0,8], x[0,64]); avx_bytemask(r[8,8], x[64,64]); r[16,16] = 0;\n    Reg32 = r;\n    build check_Reg32_dest;",
    ("VPMOVMSKB", "Reg32,YmmReg2"):
        "    local x:16 = YmmReg2_L;\n    local y:16 = YmmReg2_H;\n    local r:4;\n"
        "    avx_bytemask(r[0,8], x[0,64]); avx_bytemask(r[8,8], x[64,64]);\n"
        "    avx_bytemask(r[16,8], y[0,64]); avx_bytemask(r[24,8], y[64,64]);\n    Reg32 = r;\n    build check_Reg32_dest;",
})


def constructor_manual(name: str, operands: str, pattern: str, shape: str, body: str) -> str:
    pattern = pattern.replace("(XmmReg1 & ZmmReg1)", "(XmmReg1 & YmmReg1)")
    pattern = pattern.replace("(YmmReg1 & ZmmReg1)", "YmmReg1")
    pre = []
    if "YmmReg2_m256" in shape:
        pattern = pattern.replace("... & YmmReg2_m256", "... & YmmReg2_m256 & YmmReg2_m256_L & YmmReg2_m256_H")
        pre += ["    local lo:16 = YmmReg2_m256_L;", "    local hi:16 = YmmReg2_m256_H;"]
    elif "XmmReg2_m128" in shape:
        pre.append("    local m:16 = XmmReg2_m128;")
    elif "XmmReg2_m64" in shape:
        pre.append("    local m:8 = XmmReg2_m64;")
    elif "XmmReg2_m32" in shape:
        pre.append("    local m:4 = XmmReg2_m32;")
    elif "XmmReg2_m16" in shape:
        pre.append("    local m:2 = XmmReg2_m16;")
    if shape == "Reg32,YmmReg2":
        pattern = re.sub(r"\bYmmReg2\b", "YmmReg2 & YmmReg2_L & YmmReg2_H", pattern, count=1)
    if "YmmReg1_H" in body:
        pattern = re.sub(r"\bYmmReg1\b", "(YmmReg1 & XmmReg1 & YmmReg1_H)", pattern, count=1)
    if "check_Reg32_dest" in body and "check_Reg32_dest" not in pattern:
        pattern = pattern.replace("Reg32", "Reg32 & check_Reg32_dest", 1)
    return f":{name} {operands} is {pattern}\n{{\n" + "\n".join(pre + [body]) + "\n}\n"


def lane128_body(template: str, d: tuple[str, str], a: tuple[str, str], b: tuple[str, str] | None) -> str:
    """Bind every source qword to a fresh local so a template may slice it
    (`{a0}[0,32]`), since a bit range of a bit range is not SLEIGH."""
    _LANE_COUNTER[0] += 1
    k = _LANE_COUNTER[0]
    lines = [f"    local a0_{k}:8 = {a[0]};", f"    local a1_{k}:8 = {a[1]};"]
    kw = dict(d0=d[0], d1=d[1], a0=f"a0_{k}", a1=f"a1_{k}")
    if b:
        lines += [f"    local b0_{k}:8 = {b[0]};", f"    local b1_{k}:8 = {b[1]};"]
        kw.update(b0=f"b0_{k}", b1=f"b1_{k}")
    body = template.format(**kw)
    # locals declared in a template must be unique per expansion too
    body = re.sub(r"\blocal (\w+):", lambda m: f"local {m.group(1)}_{k}:", body)
    for name in set(re.findall(r"local (\w+)_%d:" % k, body)):
        body = re.sub(r"\b%s\b(?!_%d)" % (name, k), f"{name}_{k}", body)
    lines.append("    " + body.replace("; ", ";\n    ").rstrip())
    return "\n".join(lines)


def constructor_128_lane(name: str, operands: str, pattern: str, template: str, arity: int) -> str:
    pattern = pattern.replace("(XmmReg1 & ZmmReg1)", "(XmmReg1 & YmmReg1)")
    lines = ["    local m:16 = XmmReg2_m128;"]
    if arity == 2:
        lines.append("    local va:16 = vexVVVV_XmmReg;")
        a = ("va[0,64]", "va[64,64]"); b = ("m[0,64]", "m[64,64]")
    else:
        a = ("m[0,64]", "m[64,64]"); b = None
    lines.append(lane128_body(template, ("YmmReg1[0,64]", "YmmReg1[64,64]"), a, b))
    lines.append("    avx_zero_upper(YmmReg1);")
    return f":{name} {operands} is {pattern}\n{{\n" + "\n".join(lines) + "\n}\n"


def constructor_256_lane(name: str, operands: str, pattern: str, template: str, arity: int) -> str:
    pattern = pattern.replace("(YmmReg1 & ZmmReg1) ... & YmmReg2_m256",
                              "(YmmReg1 & YmmReg2_m256) ... & YmmReg2_m256_L & YmmReg2_m256_H")
    if arity == 2:
        pattern = pattern.replace("& vexVVVV_YmmReg;",
                                  "& vexVVVV_YmmReg & vexVVVV_YmmReg_L & vexVVVV_YmmReg_H;")
    assert "YmmReg2_m256_L" in pattern, (name, pattern)
    lines = ["    local lo:16 = YmmReg2_m256_L;", "    local hi:16 = YmmReg2_m256_H;"]
    if arity == 2:
        lines += ["    local vlo:16 = vexVVVV_YmmReg_L;", "    local vhi:16 = vexVVVV_YmmReg_H;"]
        lines.append(lane128_body(template, ("YmmReg1[0,64]", "YmmReg1[64,64]"),
                                  ("vlo[0,64]", "vlo[64,64]"), ("lo[0,64]", "lo[64,64]")))
        lines.append(lane128_body(template, ("YmmReg1[128,64]", "YmmReg1[192,64]"),
                                  ("vhi[0,64]", "vhi[64,64]"), ("hi[0,64]", "hi[64,64]")))
    else:
        lines.append(lane128_body(template, ("YmmReg1[0,64]", "YmmReg1[64,64]"),
                                  ("lo[0,64]", "lo[64,64]"), None))
        lines.append(lane128_body(template, ("YmmReg1[128,64]", "YmmReg1[192,64]"),
                                  ("hi[0,64]", "hi[64,64]"), None))
    return f":{name} {operands} is {pattern}\n{{\n" + "\n".join(lines) + "\n}\n"


def constructor_shift(name: str, operands: str, pattern: str, macro: str, shape: str) -> str:
    """Shift forms: `dst, vvvv, xmm/m128` (count in the low qword) at both
    widths, and `vvvv, reg, imm8` where vvvv is the destination."""
    if shape == "XmmReg1,vexVVVV_XmmReg,XmmReg2_m128":
        pattern = pattern.replace("(XmmReg1 & ZmmReg1)", "(XmmReg1 & YmmReg1)")
        body = ("    local m:16 = XmmReg2_m128;\n    local n:8 = m[0,64];\n"
                f"    {macro}(YmmReg1[0,64], vexVVVV_XmmReg[0,64], n);\n"
                f"    {macro}(YmmReg1[64,64], vexVVVV_XmmReg[64,64], n);\n"
                "    avx_zero_upper(YmmReg1);")
    elif shape == "YmmReg1,vexVVVV_YmmReg,XmmReg2_m128":
        pattern = pattern.replace("(YmmReg1 & ZmmReg1)", "YmmReg1")
        pattern = pattern.replace("& vexVVVV_YmmReg;", "& vexVVVV_YmmReg & vexVVVV_YmmReg_L & vexVVVV_YmmReg_H;")
        body = ("    local m:16 = XmmReg2_m128;\n    local n:8 = m[0,64];\n"
                f"    {macro}(YmmReg1[0,64], vexVVVV_YmmReg_L[0,64], n);\n"
                f"    {macro}(YmmReg1[64,64], vexVVVV_YmmReg_L[64,64], n);\n"
                f"    {macro}(YmmReg1[128,64], vexVVVV_YmmReg_H[0,64], n);\n"
                f"    {macro}(YmmReg1[192,64], vexVVVV_YmmReg_H[64,64], n);")
    elif shape == "vexVVVV_XmmReg,XmmReg2,imm8":
        # vvvv names the destination; write it as the YMM it sits in.
        pattern = pattern.replace("& vexVVVV_XmmReg;", "& vexVVVV_XmmReg & vexVVVV_YmmReg;")
        body = ("    local n:8 = zext(imm8);\n"
                f"    {macro}(vexVVVV_YmmReg[0,64], XmmReg2[0,64], n);\n"
                f"    {macro}(vexVVVV_YmmReg[64,64], XmmReg2[64,64], n);\n"
                "    avx_zero_upper(vexVVVV_YmmReg);")
    elif shape == "vexVVVV_YmmReg,YmmReg2,imm8":
        pattern = pattern.replace("& YmmReg2)", "& YmmReg2 & YmmReg2_L & YmmReg2_H)")
        body = ("    local n:8 = zext(imm8);\n"
                "    local lo:16 = YmmReg2_L;\n    local hi:16 = YmmReg2_H;\n"
                f"    {macro}(vexVVVV_YmmReg[0,64], lo[0,64], n);\n"
                f"    {macro}(vexVVVV_YmmReg[64,64], lo[64,64], n);\n"
                f"    {macro}(vexVVVV_YmmReg[128,64], hi[0,64], n);\n"
                f"    {macro}(vexVVVV_YmmReg[192,64], hi[64,64], n);")
    else:
        raise AssertionError((name, shape))
    return f":{name} {operands} is {pattern}\n{{\n{body}\n}}\n"


def packed_file(inventory: list[dict]) -> tuple[str, set[str]]:
    out = [
        "#@family avx\n"
        "# The regular three-operand packed AVX and AVX2 forms, on 64-bit lanes.\n"
        "# Generated by scripts/avx_gen.py; do not edit. The lane macros live in\n"
        "# avx_macros.sinc, the half-width operands in avx_operands.sinc, and the\n"
        "# irregular instructions in avx_manual.sinc / avx2_manual.sinc.\n\n"
    ]
    done: set[str] = set()
    seen_headers: set[str] = set()
    for row in inventory:
        name = row["name"]
        shape = re.sub(r"\s+", "", row["operands"])
        key = (name, shape)
        if key in seen_headers:
            continue
        text = None
        if name in TABLE:
            macro, arity = TABLE[name]
            expect = SHAPE_3 if arity == 2 else SHAPE_2
            if shape in expect:
                gen = constructor_128 if shape.startswith("Xmm") else constructor_256
                text = gen(name, row["operands"], row["pattern"], macro, arity)
        elif name in TABLE_VSHIFT:
            if shape in SHAPE_3:
                gen = constructor_128 if shape.startswith("Xmm") else constructor_256
                text = gen(name, row["operands"], row["pattern"], TABLE_VSHIFT[name], 2)
        elif name in TABLE_128:
            template, arity = TABLE_128[name]
            expect = SHAPE_3 if arity == 2 else SHAPE_2
            if shape in expect:
                gen = constructor_128_lane if shape.startswith("Xmm") else constructor_256_lane
                text = gen(name, row["operands"], row["pattern"], template, arity)
        elif name in TABLE_SHIFT:
            text = constructor_shift(name, row["operands"], row["pattern"], TABLE_SHIFT[name], shape)
        elif (name, shape) in MANUAL:
            text = constructor_manual(name, row["operands"], row["pattern"], shape, MANUAL[(name, shape)])
        if text is None:
            continue
        seen_headers.add(key)
        out.append(f"# {name}\n")
        if "Reg64" in shape or "rm64" in shape:
            # Only assembled into the 64-bit specification.
            text = "@ifdef IA64\n" + text + "@endif\n"
        out.append(text)
        out.append("\n")
        done.add(name)
    return "".join(out), done


def main() -> int:
    inventory = json.loads(INVENTORY.read_text())
    (X86 / "avx_macros.sinc").write_text(macro_library())
    packed, done = packed_file(inventory)
    (X86 / "avx.sinc").write_text(packed)
    (X86 / "avx2.sinc").write_text(
        "#@family avx\n"
        "# Reserved for AVX2-only forms that need their own file. The 256-bit\n"
        "# integer forms are generated into avx.sinc beside their 128-bit\n"
        "# siblings. Generated by scripts/avx_gen.py; do not edit.\n"
    )
    missing = sorted((set(TABLE) | set(TABLE_128) | set(TABLE_SHIFT) | set(TABLE_VSHIFT) | {n for n, _ in MANUAL}) - done)
    if missing:
        print("no inventory match for:", " ".join(missing), file=sys.stderr)
    print(f"generated {len(done)} mnemonics")
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
